rootUrl: http://localhost:8080
gridUrl: http://127.0.0.1:4444/wd/hub
calibrate: false
screenshotsDir: './shots'

browsers:
  chrome:
    desiredCapabilities:
      browserName: chrome

sets:
  chrome:
    files:
      - ./tests.js